# supervisord.conf
[supervisord]
nodaemon=true ; працювати на передньому плані = тримати PID 1 живим
[program:prometheus]
command=/bin/prometheus --config.file=/etc/prometheus/prometheus.yml
autorestart=true
[program:alertmanager]
command=/bin/alertmanager --config.file=/etc/alertmanager/alertmanager.yml
autorestart=true
[program:grafana]
command=/run.sh ; штатний entrypoint образу grafana
autorestart=true
[program:node_exporter]
command=/bin/node_exporter
autorestart=true
[program:cadvisor]
command=/usr/bin/cadvisor -logtostderr
autorestart=true