[supervisord]
nodaemon=true
user=root

[program:prometheus]
command=/usr/bin/prometheus --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/var/lib/prometheus
autorestart=true

[program:alertmanager]
command=/usr/bin/alertmanager --config.file=/etc/alertmanager/alertmanager.yml --storage.path=/var/lib/prometheus
autorestart=true

[program:grafana]
command=/usr/bin/grafana-server server --homepath=/usr/share/grafana --config=/usr/share/grafana/conf/defaults.ini
autorestart=true

[program:node_exporter]
command=/usr/bin/node_exporter
autorestart=true