[supervisord]
nodaemon=true ; працювати на передньому плані = тримати PID 1 живим

[unix_http_server]
file=/var/run/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[program:prometheus]
command=/bin/prometheus --config.file=/etc/prometheus/prometheus.yml
autorestart=true

[program:alertmanager]
command=/bin/alertmanager --config.file=/etc/alertmanager/alertmanager.yml
autorestart=true

[program:grafana]
command=/grafana-root/run.sh
autorestart=true

[program:node_exporter]
command=/bin/node_exporter
autorestart=true

#[program:cadvisor]
#command=/usr/bin/cadvisor -logtostderr
#autorestart=true